### ISSUE TITLE
OPAQUE Implementation?

### ISSUE THREAD

**Issue by ecorm** [jedisct1/cpace#2]
Are there any plans for an OPAQUE implementation on top of libsodium, now that it has been [recommended by the CFRG](https://mailarchive.ietf.org/arch/msg/cfrg/LKbwodpa5yXo6VuNDU66vt_Aca8/)?

**Comment by jedisct1** [comment]
If someone does it, probably 😀

But this is unlikely to be me unless I ever need this.

**Comment by ecorm** [comment]
Thank you for the quick response. No pressure, BTW. I was just curious if this was something you were planning.
